### PR TITLE
Add evaluation order tests for issues 1327 and 1433

### PR DESCRIPTION
**Pull request by kinke**
DMD 2.071 throws a RangeError for the test regarding https://github.com/ldc-developers/ldc/issues/1433.
So I'm unsure what the correct/desirable behavior is.

### CODE REVIEW

**Comment by kinke** [comment]
Any opinions on whether the pointer is to be evaluated before or after evaluating the bounds?

**Comment by JohanEngelen** [comment]
Section Slice Expressions of https://dlang.org/spec/expression.html :

> ```
SliceExpression:
    PostfixExpression [ ]
    PostfixExpression [ Slice ,opt ]
Slice:
    AssignExpression
    AssignExpression , Slice
    AssignExpression .. AssignExpression
    AssignExpression .. AssignExpression , Slice
```
PostfixExpression is evaluated. if PostfixExpression is an expression of type static array or dynamic array, the special variable $ is declared and set to be the length of the array. A new declaration scope is created for the evaluation of the AssignExpression..AssignExpression and $ appears in that scope only.

The way I read that: `getBase()` should be evaluated first, because a potential `$` in the bounds depends on it.
So to me it looks like your test is correct.

**Comment by kinke** [comment]
The base expression (`getBase()`) is to be evaluated first, that's clear. What's unclear is when its pointer is to be loaded. I deferred it to after the bounds have been evaluated, so that they may tamper with the base's pointer. If it was loaded before the bounds in that test, it'd obviously be null, as it's only set by `getUpperBound()`.

**Comment by JohanEngelen** [comment]
Ah, thanks for the explanation.
In that case, I think the full thing should be evaluated (with a conceptual copy of its state) before evaluating the others, so load `getBase().ptr` before the bounds. But I am no expert at all.

**Comment by kinke** [comment]
Closing this as the issues need to be separated. The test for 1327 will make it shortly into dmd-testsuite; the test for 1433 has been superseded by a more elaborate snippet in http://forum.dlang.org/post/blkpasccoceipqvbkyla@forum.dlang.org.

**Pull request closed without merging**
