### PR TITLE
Add DragonFly bootstrap support (ltsmaster)

### PR DESCRIPTION
**Pull request by dkgroot**
Related PR's:
- ldc
  - [ldc:ltsmaster](https://github.com/ldc-developers/ldc/pull/2461)
  - druntime:ltsmaster
    - [base PR](https://github.com/ldc-developers/druntime/pull/109)
    - [/src/core/sys/posix](https://github.com/ldc-developers/druntime/pull/111)
    - [/src/core/sys/dragonflybsd](https://github.com/ldc-developers/druntime/pull/110)
  - [phobos:ltsmaster](https://github.com/ldc-developers/phobos/pull/45)
  - [dmd-testsuite:ltsmaster](https://github.com/ldc-developers/dmd-testsuite/pull/28)

- dlang:
  - [dlang/dmd:master](https://github.com/dlang/dmd/pull/7463)
  - dlang/druntime:master
    - [dlang/druntime:master](https://github.com/dlang/druntime/pull/1999)
    - [dlang/druntime:master/src/core/sys/dragonflybsd](https://github.com/dlang/druntime/pull/2002)
    - [dlang/druntime:master/src/core/sys/posix](https://github.com/dlang/druntime/pull/2001)
  - [dlang/phobos:master](https://github.com/dlang/phobos/pull/5950) (merged already)

### CODE REVIEW

**Comment by joakim-noah** [comment]
I see that you've submitted a version of this upstream also.  I suggest you limit this pull to only changes you didn't need upstream, which should be easy since it's so small.

**Comment by dkgroot** [comment]
@joakim-noah Is it ok for me to leave them a little longer (until the dmd pr is accepted). That way i can run all the unittests smoothly.

**Comment by joakim-noah** [comment]
Yep, no problem, just saying what will be needed then.

**Comment by dkgroot** [comment]
@joakim-noah Everything is finally merged in (dlang) dmd, druntime and phobos (Also in part thanks to you). Now I need to figure out what needs to be backported here.

**Comment by joakim-noah** [comment]
I'll do it, just let me know if I miss anything.

**Comment by joakim-noah** [comment]
I don't really want to do it. 😝 Go ahead and update this patch to what you got merged upstream and is necessary for this branch, and I'll pull it.

**Comment by joakim-noah** [comment]
Only DragonFly PR left, would be good to get this in before the 0.17.6 release.

**Comment by dkgroot** [comment]
@joakim-noah Looking at it right now, to see if/what needs to be updated

**Comment by dkgroot** [comment]
@joakim-noah 
The Makefile needed touching up (to match the dlang/dmd/test/Makefile one). The other two changes already matched.

**Comment by dkgroot** [comment]
Thanks !!

**Pull request merged**
